# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
env_files:
  github_token: ./GHTOKEN
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X github.com/slashformotion/radioboat/internal/buildinfo.Version={{.Version}} -X github.com/slashformotion/radioboat/internal/buildinfo.Commit={{.Commit}} -X github.com/slashformotion/radioboat/internal/buildinfo.BuildDate={{.Date}} -X github.com/slashformotion/radioboat/internal/buildinfo.VendorInfo=goreleaser 
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^.vscode:'
      - '^test:'
      - '^.github:'
