name: Build 

on:
  push:
    branches: [ '**' ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  golang_build:
    name: Build Radioboat
    strategy:
      matrix:
        go_version: ['1.18.x', '1.19.x']
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v .

    - name: Upload binary 
      uses: actions/upload-artifact@v1
      with:
        name: binary_${{ matrix.go_version }}
        path: ./radioboat