name: Test 

on:
  push:
    branches: [ '**' ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  golang_test:
    name: Test Radioboat

    strategy:
      matrix:
        go_version: ['1.18.x', '1.19.x']
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: go test -json ./... > test.json

    - name: Annotate tests
      if: always()
      uses: guyarb/golang-test-annotations@v0.5.1
      with:
        test-results: test.json
        # package-name: radioboat # optional, if using custom package name, github.com/owner/repo stripped from the pathname by default

